<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="div container">
    <div class="jumbotron">
        <h1 class="display-4">Sobre</h1>
    </div>
    <div class="div col-md12">
        <h2>A Instituição</h2>
        <p class="text-justify">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad alias atque aut deleniti eum eveniet
            fugiat illum libero veniam? Dolores, perferendis, veritatis! Animi dolorem earum ipsa repellendus
            similique sit.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad alias atque aut deleniti eum eveniet
            fugiat illum libero veniam? Dolores, perferendis, veritatis! Animi dolorem earum ipsa repellendus
            similique sit.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad alias atque aut deleniti eum eveniet
            fugiat illum libero veniam? Dolores, perferendis, veritatis! Animi dolorem earum ipsa repellendus
            similique sit.

        </p>
        <h2>Nossas Metas</h2>
        <p class="text-justify">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad alias atque aut deleniti eum eveniet
            fugiat illum libero veniam? Dolores, perferendis, veritatis! Animi dolorem earum ipsa repellendus
            similique sit.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad alias atque aut deleniti eum eveniet
            fugiat illum libero veniam? Dolores, perferendis, veritatis! Animi dolorem earum ipsa repellendus
            similique sit.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad alias atque aut deleniti eum eveniet
            fugiat illum libero veniam? Dolores, perferendis, veritatis! Animi dolorem earum ipsa repellendus
            similique sit.

        </p>

        <h2>Valores</h2>
        <p class="text-justify">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad alias atque aut deleniti eum eveniet
            fugiat illum libero veniam? Dolores, perferendis, veritatis! Animi dolorem earum ipsa repellendus
            similique sit.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad alias atque aut deleniti eum eveniet
            fugiat illum libero veniam? Dolores, perferendis, veritatis! Animi dolorem earum ipsa repellendus
            similique sit.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab ad alias atque aut deleniti eum eveniet
            fugiat illum libero veniam? Dolores, perferendis, veritatis! Animi dolorem earum ipsa repellendus
            similique sit.

        </p>
    </div>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>

