<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="div container">
    <div class="jumbotron">
        <h1 class="display-4">Bem Vindo ao Site</h1>
        <p class="lead">Projeto criando site institucional em PHP e MVC</p>

        <a class="btn btn-primary btn-lg" href="https://github.com/JulioPaschoal" role="button">Learn more</a>
    </div>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>

